### ISSUE TITLE
Compile Error on usage

### ISSUE THREAD

**Issue by evoactivity** [Socivo/ember-cli-intl-tel-input#1]
`intl-tel-input is not a helper`

I'm using Ember 2.16.0

Twiddle setup here
https://ember-twiddle.com/9f99a329bd4454c8186a60decb941085?openFiles=templates.application.hbs%2C

**Comment by evoactivity** [comment]
That would be because it's now exported as `ember-cli-intl-tel-input` what would be the reason for this?

**Comment by MojoJojo** [comment]
Hi,

Thanks for bringing it to my attention. I'm not sure - I haven't tested it with the latest EmberJS. Will fix it over the weekend and publish a new version.

**Comment by MojoJojo** [comment]
Hi..
Quick feedback ..the plugin exports the template as ember-cli-intl-tel-input ...was done to keep it separate from other plugins using the same namespace.

I am going to refactor it to remove bower dependecies and fix the exported namespace. Will publish a new version later today.

Thank you for your patience!

**Comment by evoactivity** [comment]
@MojoJojo Good to hear :)

Another issue I ran into was the vendor css wasn't added to my vendor file, I had a quick look into that but couldn't replicate on ember twiddle. I don't have time to look into that this week but I might have some time to have a look next week.

**Comment by monica-olejniczak-safetyculture** [comment]
@MojoJojo Hey! What's the status on this?

@MojoJojo @evoactivity I ran into the same issue. If you add `ember-cli-sass` in your `dependencies` (not `devDependencies`!) it fixes the issue.

**Comment by MojoJojo** [comment]
@evoactivity @monica-olejniczak-safetyculture Will publish the fixed version on npm today.

Thank you for your patience!

**Comment by monica-olejniczak-safetyculture** [comment]
@MojoJojo Awesome, thanks! While you're at it with updating, can you use the newer intl-tel-input options?

This includes:

- Add `allowDropdown` (defaults to true)
- Remove `autoFormat` option (got removed)
- Add `customPlaceholder`, a function that defaults to null.
- Add `dropdownContainer` (defaults to "")
- Add `excludeCountries` (defaults to undefined)
- Add `formatOnDisplay` (defaults to true)
- Add `hiddenInput` (defaults to "")
- Add `placeholderNumberType` (defaults to "MOBILE")
- Add `separateDialCode` (defaults to false)

**Comment by MojoJojo** [comment]
Hi @evoactivity @monica-olejniczak-safetyculture 
Have published 1.0.8 on npm with changes and the new methods. Please have a look.

Will add tests shortly.

**Comment by dudv** [comment]
@MojoJojo Thanks for your work. Unfortunately I still get `Compile Error: intl-tel-input is not a helper`. Here's Twiddle which reproduces it https://ember-twiddle.com/381aa0707274545084745c4571db0b85.

**Comment by MojoJojo** [comment]
That's odd. Looking at it now.

**Comment by evoactivity** [comment]
@MojoJojo downgrading to 1.0.10 works so must be something in the last few commits

**Comment by temecom** [comment]
I think that you need to add a link file:
```
// app/components/intl-tel-input.js
export { default } from 'ember-cli-intl-tel-input/components/intl-tel-input';
```
and 
```
// app/templates/components/intl-tel-input.js
export { default } from 'ember-cli-intl-tel-input/templates/components/intl-tel-input';

```
Otherwise the application cannot see the addon as a component where it normally would in  
 app/components and app/templates/components

(that is unless Ember 2.18 changed the way that they handle addons :) )

**Comment by MojoJojo** [comment]
Apologies for the delayed response. Been swamped with work.

@evoactivity @temecom You are right. Not sure how I missed the component re-export file! Have updated codebase and published the new version (1.0.14)

https://ember-twiddle.com/4541d241d9e1ae653a64dac7279bb5fc?openFiles=twiddle.json%2C

**Comment by temecom** [comment]
There is no test/dummy app with samples like the original repo: 
[https://github.com/justin-lau/ember-intl-tel-input/blob/master/tests/dummy/app/templates/index.hbs](justin-lau/ember-intl-tel-input)

Is that intentional? It makes testing a lot easier :)

**Comment by MojoJojo** [comment]
*Sigh.*..its not intentional..the plugin was kind of rushed to get a project going..I will try and update it this week.

**Comment by temecom** [comment]
Sorry to be a pest :)
